# Generated by Django 2.2.1 on 2019-05-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='edition',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='state',
            field=models.CharField(choices=[('2', '待确认'), ('0', '未付款'), ('4', '已完成'), ('1', '已付款'), ('3', '待评价')], default=0, max_length=6),
        ),
    ]
