# Generated by Django 2.2.1 on 2019-05-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20190521_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='state',
            field=models.CharField(choices=[('2', '待确认'), ('0', '未付款'), ('5', '退款/售后'), ('3', '待评价'), ('4', '已完成'), ('1', '已付款')], default=0, max_length=10),
        ),
    ]
