# Generated by Django 2.2.1 on 2019-05-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20190522_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='state',
            field=models.CharField(choices=[('0', '未付款'), ('3', '待评价'), ('2', '待确认'), ('5', '退款/售后'), ('4', '已完成'), ('1', '已付款')], default=0, max_length=10),
        ),
    ]
