# Generated by Django 2.2.1 on 2019-05-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_auto_20190522_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='edition_id',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='state',
            field=models.CharField(choices=[('2', '待确认'), ('4', '已完成'), ('3', '待评价'), ('5', '退款/售后'), ('6', '已关闭'), ('1', '待发货'), ('0', '未付款')], default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_id',
            field=models.CharField(max_length=20),
        ),
    ]
