# Generated by Django 2.2.1 on 2019-05-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_auto_20190530_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='state',
            field=models.CharField(choices=[('6', '已关闭'), ('4', '已完成'), ('0', '未付款'), ('1', '待发货'), ('3', '待评价'), ('5', '退款/售后'), ('2', '待确认')], default=0, max_length=10),
        ),
    ]
