# Generated by Django 2.2.1 on 2019-05-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0002_shopping_cart_edition'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_cart',
            name='edition_id',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
