# Generated by Django 2.2.1 on 2019-05-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('intro', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disc_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
                ('commodity_type', models.CharField(choices=[('FD', '食品'), ('JE', '首饰'), ('CL', '衣物'), ('DG', '数码'), ('EL', '电器'), ('DU', '日用'), ('MD', '药品')], max_length=4)),
                ('commodity_id', models.CharField(max_length=20, unique=True)),
                ('edition', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
