# Generated by Django 2.2.1 on 2019-05-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='commodity_type',
            field=models.CharField(choices=[('CL', '衣物'), ('DU', '日用'), ('EL', '电器'), ('FD', '食品'), ('JE', '首饰'), ('DG', '数码'), ('MD', '药品')], max_length=4),
        ),
    ]
