# Generated by Django 2.2.1 on 2019-05-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0002_auto_20190521_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='commodity_type',
            field=models.CharField(choices=[('JE', '首饰'), ('DU', '日用'), ('DG', '数码'), ('MD', '药品'), ('EL', '电器'), ('FD', '食品'), ('CL', '衣物')], max_length=4),
        ),
    ]
