# Generated by Django 2.2.1 on 2019-05-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0003_auto_20190522_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='commodity_type',
            field=models.CharField(choices=[('EL', '电器'), ('DG', '数码'), ('DU', '日用'), ('CL', '衣物'), ('JE', '首饰'), ('MD', '药品'), ('FD', '食品')], max_length=4),
        ),
    ]
