# Generated by Django 2.2.1 on 2019-05-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0004_auto_20190522_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='commodity_type',
            field=models.CharField(choices=[('FD', '食品'), ('EL', '电器'), ('DG', '数码'), ('JE', '首饰'), ('MD', '药品'), ('DU', '日用'), ('CL', '衣物')], max_length=4),
        ),
    ]
