# Generated by Django 2.2.1 on 2019-05-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0005_auto_20190523_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='commodity_type',
            field=models.CharField(choices=[('DG', '数码'), ('FD', '食品'), ('DU', '日用'), ('MD', '药品'), ('CL', '衣物'), ('JE', '首饰'), ('EL', '电器')], max_length=4),
        ),
    ]
