# Generated by Django 2.2.1 on 2019-05-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0006_auto_20190530_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='commodity_type',
            field=models.CharField(choices=[('FD', '食品'), ('JE', '首饰'), ('CL', '衣物'), ('DG', '数码'), ('EL', '电器'), ('DU', '日用'), ('MD', '药品')], max_length=4),
        ),
    ]
