# Generated by Django 2.2.1 on 2019-06-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0007_auto_20190531_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='commodity_type',
            field=models.CharField(choices=[('EL', '电器'), ('CL', '衣物'), ('DU', '日用'), ('JE', '首饰'), ('MD', '药品'), ('DG', '数码'), ('FD', '食品')], max_length=4),
        ),
    ]
